# Generated by Django 5.0.3 on 2024-03-23 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id_date', models.IntegerField(primary_key=True, serialize=False)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Employé', 'Employé'), ('Responsable', 'Responsable'), ('Gestionnaire', 'Gestionnaire')], max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id_projet', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('avancement', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('En pause', 'En pause'), ('Planifié', 'Planifié'), ('En cours', 'En cours'), ('Livré', 'Livré')], max_length=50)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetmanagement.dates')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetmanagement.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Taches',
            fields=[
                ('id_tache', models.IntegerField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('niveau_profondeur', models.IntegerField()),
                ('duree', models.IntegerField()),
                ('avancement', models.DecimalField(decimal_places=2, max_digits=15)),
                ('priorite', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('statut', models.CharField(choices=[('Planifiée', 'Planifiée'), ('En cours', 'En cours'), ('Réalisée', 'Réalisée'), ('En pause', 'En pause'), ('Validée', 'Validée')], max_length=50)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetmanagement.dates')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetmanagement.projets')),
                ('tache_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetmanagement.taches')),
            ],
        ),
    ]
