# Generated by Django 5.0.3 on 2024-03-23 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taches',
            name='niveau_profondeur',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='taches',
            name='tache_parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projetmanagement.taches'),
            preserve_default=False,
        ),
    ]
