# Generated by Django 5.0.3 on 2024-03-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetmanagement', '0002_alter_taches_niveau_profondeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taches',
            name='tache_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetmanagement.taches'),
        ),
    ]
