# Generated by Django 5.0.3 on 2024-03-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetmanagement', '0003_alter_taches_tache_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projets',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='projets',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetmanagement.utilisateur'),
        ),
        migrations.AlterField(
            model_name='projets',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetmanagement.dates'),
        ),
        migrations.AlterField(
            model_name='taches',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetmanagement.dates'),
        ),
    ]
