# Generated by Django 5.0.3 on 2024-03-24 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetmanagement', '0004_remove_projets_utilisateur_projets_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taches',
            name='tache_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_taches', to='projetmanagement.taches'),
        ),
    ]
